name: Feature Request / Story
description: Propose a new feature or user story
title: "[Feature] "
labels: ["type:story", "enhancement", "priority:medium"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature! Please describe what you'd like to see.

  - type: textarea
    id: user-story
    attributes:
      label: User Story
      description: Describe the feature as a user story
      placeholder: "As a [user type], I want [goal] so that [benefit]"
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Detailed Description
      description: Provide more details about what this feature should do
    validations:
      required: true

  - type: textarea
    id: acceptance
    attributes:
      label: Acceptance Criteria
      description: How will we know this feature is complete?
      placeholder: |
        - [ ] Criterion 1
        - [ ] Criterion 2
        - [ ] Criterion 3
    validations:
      required: true

  - type: dropdown
    id: area
    attributes:
      label: Area
      description: Which part of the system does this affect?
      options:
        - Frontend
        - API/Backend
        - AR Engine
        - Compliance Checking
        - Infrastructure
        - Multiple Areas
    validations:
      required: true

  - type: dropdown
    id: size
    attributes:
      label: Estimated Size
      description: How big is this feature? (rough estimate)
      options:
        - XS (< 2 hours)
        - S (2-4 hours)
        - M (1-2 days)
        - L (3-5 days)
        - XL (1-2 weeks)
        - Unknown
    validations:
      required: true

  - type: textarea
    id: dependencies
    attributes:
      label: Dependencies
      description: Does this feature depend on other work?
      placeholder: "Depends on #123, requires API changes first"

  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Any mockups, examples, or other relevant information
